$ANSIBLE_VAULT;1.1;AES256
66663364643436663262626636313066393366373836636633366538313565313762663130623332
3535396238366339386238366631666435343031353238340a613862373163346335653133383361
38393961326231363136613664653565313137616338373361383231623334376139613932643763
6334323162383731350a353236623664666232373164343864303430393163623132666236313732
66343535643239636335373766653435346561333731616636626438306638666631383065653662
64313638613764353566373465666162306262666561323533326263653065376465303232323263
65336637356139386264373835633534363232356539616135363332396337633036633336626562
33333664336565343061
