---
lgsm:
  - user: l4dserver
    game_name: l4dserver
    directory: left4dead
    password: "{{ l4dserver_password }}"
    ssh-keys:
      - type: ssh-rsa
        key: "AAAAB3NzaC1yc2EAAAADAQABAAABAQCxq38ackhbuz+QYAOiC9PtFa5G3TERInfMVrO5HSYOt8Y4SsRl7kjjb8KC0PrqIkKxlZ7nbaOdACqKMXHLCGVDQ\
              udOALjErxTvwOcxkIqkXUbNPKcG08YPJZHmr0z6k7xxssfm059n0yJZG7c7wup16Mj7GJR2Nfqm0d6Z8Hj624On/aHgW2zX9pD+mlp3toGVMYDMCBcpfV0\
              rMn+P4iLSa3RfxL29CGW7o2RNv/YBybzavzKp+XT4Kyup6MLx/qe/9XdwXBhG7/WaByyCDED+9AJMtlpSRo3+DZsgGhA2mOmo++TlW+UNopz6GFMUc/VdGo\
              5CFtOzQbbigesTkR4P"
        comment: l4dserver@LGSM-Debian
    sourcemod_admins:
      - name: player1
        identity: STEAM_0:0:xxxxxxxxx
        flags: abcdefghijklmn
      - name: player2
        identity: STEAM_1:1:xxxxxxxxx
        flags: abcfgjk
    metamod_plugins: true
    sourcemod_plugins: true
    lgsm_cfg: true
    server_cfg: true
    serverfiles: true
    stripper_cfg: true
    maps: true
    crontab_reboot:
      - name: l4dserver_reboot_monitor
        command: monitor
        sleep: "40"
    crontab:
      - name: l4dserver_update
        minute: "*/30"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        command: update
      - name: l4dserver_update-lgsm
        minute: 10
        hour: 0
        day: "*"
        month: "*"
        weekday: 0
        command: update-lgsm
      - name: l4dserver_stop-everyday
        minute: 55
        hour: 3
        day: "*"
        month: "*"
        weekday: "*"
        command: stop
      - name: l4dserver_force-update-everyday
        minute: 56
        hour: 3
        day: "*"
        month: "*"
        weekday: "*"
        command: force-update
      - name: l4dserver_start-everyday
        minute: 57
        hour: 3
        day: "*"
        month: "*"
        weekday: "*"
        command: start
      - name: l4dserver_monitor-everyday
        minute: "3-59/5"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        command: monitor
  - user: l4d2server
    game_name: l4d2server
    directory: left4dead2
    password: "{{ l4d2server_password }}"
    ssh-keys:
      - type: ssh-rsa
        key: "AAAAB3NzaC1yc2EAAAADAQABAAABAQCNzP3WO/bxx0QZoL0waQDg9AXUfXkp93WpcuFVREfYLpLP9+23vLAInWYM7rFFzlWfpOJ7l+yByztW3jXg\
              7CtRKpiWduBFcvRMgn+FNOURcL3Y8hfOfURy8QvWMrTOqITgcwZMo35SdeEVIvDTbhBzrbBsguJzuogl76J23hz7RHCfSh+3ToTyVnbZza8eBOHC9\
              Q7EAW2bH7NDnHB/iBSNEbjXvKUQscZ56NVE3onRzaBL0wbboKH3/nRqU/bGhJt3mQKvWolh0LqfjzzGTadQ4YglfivKfD5/FaaBqQj0Oz4syWwIwQI\
              F7sBi0jB6R9jes9/uDcoe7+E5u3QqfHd"
        comment: l4d2server@LGSM-Debian
    sourcemod_admins:
      - name: player1
        identity: STEAM_0:0:xxxxxxxxx
        flags: abcdefghijklmn
      - name: player2
        identity: STEAM_1:1:xxxxxxxxx
        flags: abcfgjk
    metamod_plugins: true
    sourcemod_plugins: true
    lgsm_cfg: true
    server_cfg: true
    stripper_cfg: true
    maps: true
    serverfiles: true
    crontab_reboot:
      - name: l4d2server_reboot_monitor
        command: monitor
        sleep: "45"
    crontab:
      - name: l4d2server_update
        minute: 5,35
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        command: update
      - name: l4d2server_update-lgsm
        minute: 15
        hour: 0
        day: "*"
        month: "*"
        weekday: 0
        command: update-lgsm
      - name: l4d2server_stop-everyday
        minute: 0
        hour: 4
        day: "*"
        month: "*"
        weekday: "*"
        command: stop
      - name: l4d2server_force-update-everyday
        minute: 1
        hour: 4
        day: "*"
        month: "*"
        weekday: "*"
        command: force-update
      - name: l4d2server_start-everyday
        minute: 2
        hour: 4
        day: "*"
        month: "*"
        weekday: "*"
        command: start
      - name: l4d2server_monitor-everyday
        minute: "4-59/5"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        command: monitor

lgsmuser_steamcmd_locales_secondary: fr_FR.UTF-8 UTF-8

configure_ssh_port: 5976
configure_iptables_games_servers_ports: 27015,27016
configure_iptables_ssh_port: "{{ configure_ssh_port }}"
configure_nftables_games_servers_ports: 27015, 27016
configure_nftables_ssh_port: "{{ configure_ssh_port }}"
